### ISSUE TITLE
contentsセクション内に教室展示の一覧を作る

### ISSUE THREAD

**Issue by ckndrm** [INIAD-FES-2022/wellb-fes-2022#10]
index.html内のコンテンツセクションに、「画像・展示場所・説明文・画像・展示場所・説明文……………」の順番で教室展示の一覧を作ってください。説明文はこのパンフレットの文章をそのまま書いてください。掲載順は階数が低いかつ教室番号が若い順にお願いします。
![パンフ1F_模擬店_2F_3F_6F_01-1](https://user-images.githubusercontent.com/104750455/191902313-1d006315-c0be-4866-8383-bb4e36f01180.jpg)
![パンフ1F_模擬店_2F_3F_6F_03-1](https://user-images.githubusercontent.com/104750455/191902325-cd364fd8-f089-4115-a6c2-59e25de459f5.jpg)
![パンフ1F_模擬店_2F_3F_6F_04-1](https://user-images.githubusercontent.com/104750455/191902328-49abd629-047e-4e8e-867b-df10e0166fff.jpg)

**Comment by ckndrm** [comment]
WELLBの方に共有いただいたフォルダにpdfがあるのでそちらからなら楽に説明文を写せるかもしれません、作業量が多くなってしまいましたがよろしくお願いします🙇

**Comment by Miumaru-iniad** [comment]
了解です。

**Comment by Miumaru-iniad** [comment]
赤羽消防署の展示の画像が見当たらないので確認お願いします

**Comment by ckndrm** [comment]
共有フォルダ内に見当たらなかったのでwellbの方に確認をしてみます。とりあえずは空のimgタグを置いておいてほしいです！

**Comment by Miumaru-iniad** [comment]
ありがとうございます。6階の保育実習室も画像が内容なので合わせて確認お願いします。現状は空のimgタグを置いてあります

**Comment by ckndrm** [comment]
WELLBの方から素材をいただけたので補完しておきました！これにてクローズです。おつかれさまでした。
