### ISSUE TITLE
カウントダウンセクションをCSSで整形

### ISSUE THREAD

**Issue by ckndrm** [INIAD-FES-2022/wellb-fes-2022#13]
カウントダウンの表示を現在よりも見やすく変更してください。都度共有してほかのメンバーから意見をもらうようにするとgoodかもです！

**Comment by rit-iniad** [comment]
取り敢えず変更してみました！
どうでしょうか？

**Comment by ckndrm** [comment]
ありがとうございます！大きさちょうどいいと思います！各数字が何かぱっと見でわかるように、「32日と5:52」のように表示できるとさらに良くなるかなと思いました！

**Comment by rit-iniad** [comment]
アドバイスありがとうございます。
かいぜんしてみますね！

**Comment by rit-iniad** [comment]
例えば、残り5時間3分となるとき5:3だと分かりにくいと思い、〇〇日〇〇時間〇〇分となるようにしました！

**Comment by ckndrm** [comment]
ありがとうございます！いい感じだと思います！
