### ISSUE TITLE
固定サイドバー実装

### ISSUE THREAD

**Issue by ckndrm** [INIAD-FES-2022/wellb-fes-2022#3]
スクロールしても画面左側に固定表示されるメニューバーを実装してください。メニュー内の各要素はメインコンテンツのセクションに飛べるようにしてください。

またスマホ版表示ではこのサイドバーが非表示になり、ヘッダーのハンバーガーメニューを押すことでメニューが左から出現する仕様になります。

**Comment by MATCHAo2** [comment]
![スクリーンショット 2022-09-19 4 58 19](https://user-images.githubusercontent.com/69121426/190926015-b576d13a-0f24-4d9b-a3aa-c8deca981762.png)

迅速果敢な対応、ありがとうございます！🙇‍♂️

ご存知とは思うのですが、一応コメントを残させていただきま
す…

- [x] メニューバーなんですが、高さが足りなさそうです(上のスクショの通り
  - ウィンドウを変形してもメニューバーが下まで伸びてくれると良さげかも
- [x] ハンバーガーメニュー、ボタンは出るんですがメニューが出ません

**Comment by ckndrm** [comment]
メニューバーの高さはもう一度確認してみます。ハンバーガーメニューについては昨晩pushしたものではしっかり動くようになったと思います！

**Comment by ckndrm** [comment]
いまコードを確認してメニューバーの高さを改善いたしました。

**Comment by MATCHAo2** [comment]
対応ありがとうございました！OKです！
