### ISSUE TITLE
メインコンテンツ仮置き

### ISSUE THREAD

**Issue by ckndrm** [INIAD-FES-2022/wellb-fes-2022#4]
セクションのタイトル、サンプル画像(適当なものでかまいません)、本文(テキストテキストテキストみたいなのでOK)をワイヤーフレームを確認しながら置いてください。
CSSは構造を作るための必要最低限の分だけでかまいません。

※カウントダウンの部分はdivで箱だけ作っていただければ結構です。

**Comment by MATCHAo2** [comment]
これって村野くんがCSS整えるのと一緒にやってくれた感じ？

**Comment by ckndrm** [comment]
セクションつくりは村野君がcssと一緒にやってくれて、サンプルテキストとかデモ画像をいれる作業は宇野君がやってくれました。
