### ISSUE TITLE
カウントダウン実装

### ISSUE THREAD

**Issue by ckndrm** [INIAD-FES-2022/wellb-fes-2022#5]
JSを使って学祭当日にカウントダウンが00:00:00になるように更新し続けるタイマーを実装してください。
https://countdown.reportitle.com/
このツールを使って機能を実装すると楽かもしれません。細かいパーツの整形はCSS担当者に任せていただいて結構です。

**Comment by Miumaru-iniad** [comment]
確認しました。
https://mgmgblog.com/?p=2595
ひとまずこれに沿って実装してみます

**Comment by MATCHAo2** [comment]
ありがとうございます。よろしくお願いします🙏

**Comment by Miumaru-iniad** [comment]
コードを追加して動作の確認が出来たので一度pushさせていただきました。
対応が遅くなってしまいすみませんでした。

**Comment by MATCHAo2** [comment]
迅速な対応、ありがとうございました！
カウントダウンに秒数を含めるかどうかは今後WELLBの方に確認しますね。
