### ISSUE TITLE
【メインコンテンツ仮置き後】CSSでメインコンテンツをきれいにする

### ISSUE THREAD

**Issue by ckndrm** [INIAD-FES-2022/wellb-fes-2022#6]
idやclassを使ってfigmaのようにブロックごとに角の取れた半透明の背景を作ってください。
figmaではパススルー40%, 角半径15%で実装しています。(コンテンツの大きさが異なってくると思うので、角半径は目分量できれいになるよう調整してください。)

※もし余裕があればパススルーではなくガラスのような質感の背景にしてみると綺麗かもしれません。参考サイトを一つ貼っておくので、できそうであれば実装していただきたいです。

https://web-dev.tech/front-end/css/glassmorphism/

その他にも気になった部分があれば見やすさを損なわない程度に自由に変更していただいて構いません。

**Comment by rit-iniad** [comment]
了解です。
これから作業に取り掛かります！！

**Comment by rit-iniad** [comment]
おおよそできたのですがどうでしょうか？

**Comment by MATCHAo2** [comment]
部長です
めっちゃ良いと思います！ありがとう！
今後開発を進める上で何かしら不都合が生じるかもしれません。その際は対応をお願いしますね🙇‍♂️

**Comment by rit-iniad** [comment]
了解致しました！

**Comment by MATCHAo2** [comment]
お疲れ様です〜
コンソールを見たらbg.jpgがないよ〜ってエラーが出てました
背景の素材が共有されたら背景を差し込む形になると思いますので、これ自体は問題ないんですが、このパスの設定だとcssフォルダ内のbg.jpg(css/bg.jpg)を参照する形となります。写真の素材を一箇所のフォルダにまとめるのであれば、相対パスを使ってフォルダの場所を指定してあげると良いかなと思いました(../img/bg.jpg みたいな感じで)
